config/routes.rb
AdaCooks::Application.routes.draw do
  get "static/index"
  resources :tools

  resources :ingredients

  resources :recipes

  resources :cookbooks

  resources :users

  root 'static#index'

  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  attr_accessor :matches

  has_many :cookbook_recipes
  has_many :cookbooks, through: :cookbook_recipes
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :recipe_tools
  has_many :tools, through: :recipe_tools

  def self.ingredients_match(search)
    @matches = includes(:ingredients).where(ingredients: {name: search})
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    #@matching_recipes = Recipe.search(params[:search])
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    params[:recipe][:cookbooks].each do |cookbook_id|
      next if cookbook_id.to_i == 0
      cookbook = Cookbook.find(cookbook_id.to_i)
      @recipe.cookbooks << cookbook
    end

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        params[:recipe][:cookbooks].each do |cookbook_id|
          next if cookbook_id.to_i == 0
          cookbook = Cookbook.find(cookbook_id.to_i)

          @recipe.cookbooks << cookbook
        end

        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :description, :process, :vegan, :vegetarian, :GF, :cookbooks => {})
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
    <% if @recipe.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

            <ul>
                <% @recipe.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>


    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <!--User should be able to add this recipe to one of the cookbooks that the user has already created-->
    <!--User should be able to add n ingredients to each recipe-->

    <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>

    <div class="field">
        <%= f.label :instructions %>
        <%= f.text_area :instructions %>
    </div>

    <div class="field">
        <%= f.label :vegan %>
        <%= f.check_box :vegan %>
    </div>

    <div class="field">
        <%= f.label :vegetarian %>
        <%= f.check_box :vegetarian %>
    </div>

    <div class="field">
        <%= f.label :GF %>
        <%= f.check_box :GF %>
    </div>

    <!-- This gives a select box containing the cookbooks which the recipe is in. It also highlights them correctly
    when editing -->
    <p>Choose the cookbook(s) where this recipe will go:</p>
    <%= select(:cookbook_recipes,
               :recipe_id,
               Cookbook.all.collect { |p| [p.name, p.id] },
               {:selected => CookbookRecipe.where(:recipe_id => @recipe.id).map(&:cookbook_id)},
               {'name' => 'recipe[cookbooks][]', :multiple => true}) %>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
    <thead>
    <tr>
        <th>Recipe</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    </thead>

    <tbody>
    <% if not params[:search].nil? %>
        <% Recipe.ingredients_match(params[:search]).each do |match| %>
            <tr>
                <td><%= match.name %></td>
                <td><%= link_to 'Show', match %></td>
                <td><%= link_to 'Edit', edit_recipe_path(match) %></td>
                <td><%= link_to 'Destroy', match, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>

    <% else %>
        <% @recipes.each do |recipe| %>
            <tr>
                <td><%= recipe.name %></td>
                <td><%= link_to 'Show', recipe %></td>
                <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
                <td><%= link_to 'Destroy', recipe, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
    <% end %>


    </tbody>
</table>

<br>

<strong><%= link_to 'New Recipe', new_recipe_path %></strong>


<p>Search for a recipe</p>

<%= form_tag("/recipes", method: "get") do %>
    <p>
        <%= label_tag(:search) %>
        <%= text_field_tag :search %>
        <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>


<br>

<div class="navbar">
    <a href="/users">Back to Users</a>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Name:</strong>
    <%= @recipe.name %>
</p>

<p>
    <strong>Description:</strong>
    <%= @recipe.description %>
</p>

<p>
    <strong>Method:</strong>
    <%= @recipe.instructions %>
</p>

<p>
    <strong>Categories:</strong>
    Vegan: <%= @recipe.vegan %><br>
    Vegetarian:<%= @recipe.vegetarian %><br>
    Gluten Free:<%= @recipe.GF %>
</p>

<p><strong>Cookbooks:</strong>
    <% @recipe.cookbooks.each do |cookbook| %>
    <%= cookbook.name %>
        <% end %>
    <br>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %>
<%= link_to 'Back', recipes_path %>