config/routes.rb
AdaCooks::Application.routes.draw do
  get "static/index"
  resources :tools

  resources :ingredients

  resources :recipes

  resources :cookbooks

  resources :users

  root 'static#index'

  

end

app/models/cookbook.rb
class Cookbook < ActiveRecord::Base
  belongs_to :user
  has_many :cookbook_recipes
  has_many :recipes, through: :cookbook_recipes
  has_many :cookbook_tools
  has_many :tools, through: :cookbook_tools
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  before_action :set_cookbook, only: [:show, :edit, :update, :destroy]

  # GET /cookbooks
  # GET /cookbooks.json
  def index
    @cookbooks = Cookbook.all
  end

  # GET /cookbooks/1
  # GET /cookbooks/1.json
  def show
  end

  # GET /cookbooks/new
  def new
    @cookbook = Cookbook.new
  end

  # GET /cookbooks/1/edit
  def edit
  end

  # POST /cookbooks
  # POST /cookbooks.json
  def create
    @cookbook = Cookbook.new(cookbook_params)

    respond_to do |format|
      if @cookbook.save
        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cookbook }
      else
        format.html { render action: 'new' }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cookbooks/1
  # PATCH/PUT /cookbooks/1.json
  def update
    respond_to do |format|
      if @cookbook.update(cookbook_params)
        params[:cookbook][:recipes].each do |recipe_id|
          next if recipe_id.to_i == 0
          recipe = Recipe.find(recipe_id.to_i)

          @cookbook.recipes << recipe

          params[:cookbook][:tools].each do |tool_id|
            next if tool_id.to_i == 0
            tool = Tool.find(tool_id.to_i)

            @cookbook.tools << tool
          end
        end

        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookbooks/1
  # DELETE /cookbooks/1.json
  def destroy
    @cookbook.destroy
    respond_to do |format|
      format.html { redirect_to cookbooks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cookbook
      @cookbook = Cookbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cookbook_params
      params.require(:cookbook).permit(:user_id, :name, :recipes => {}, :tools => {})
    end
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/views/cookbooks/_form.html.erb
<%= form_for(@cookbook) do |f| %>
  <% if @cookbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cookbook.errors.count, "error") %> prohibited this cookbook from being saved:</h2>

      <ul>
      <% @cookbook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

    <div class="select_boxes">
    <p>Choose the recipes you'd like to have in this cookbook:</p>
    <%= select(:cookbook_recipes,
               :cookbook_id,
               Recipe.all.collect { |p| [p.name, p.id] },
               {:selected => CookbookRecipe.where(:cookbook_id => @cookbook.id).map(&:recipe_id)},
               {'name' => 'cookbook[recipes][]', :multiple => true}) %>

    <p>Choose the tools you'd like to have in this cookbook:</p>
    <%= select(:cookbook_tools,
               :cookbook_id,
               Tool.all.collect { |p| [p.name, p.id] },
               {:selected => CookbookTool.where(:cookbook_id => @cookbook.id).map(&:tool_id)},
               {'name' => 'cookbook[tools][]', :multiple => true}) %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cookbooks/edit.html.erb
<h1>Editing cookbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @cookbook %> |
<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/index.html.erb
<h1>Listing cookbooks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cookbooks.each do |cookbook| %>
      <tr>
        <td><%= cookbook.user_id %></td>
        <td><%= cookbook.name %></td>
        <td><%= link_to 'Show', cookbook %></td>
        <td><%= link_to 'Edit', edit_cookbook_path(cookbook) %></td>
        <td><%= link_to 'Destroy', cookbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<strong><%= link_to 'New Cookbook', new_cookbook_path %></strong>

<br>

<div class="navbar">
    <a href="/users">Back to Users</a>
</div>

app/views/cookbooks/new.html.erb
<h1>New cookbook</h1>

<%= render 'form' %>

<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cookbook.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cookbook.name %>
</p>

<p><strong>Recipes:</strong>
    <% @cookbook.recipes.each do |recipe| %>
        <%= recipe.name %>
    <% end %>
    <br>
</p>

<p><strong>Tools:</strong>
    <% @cookbook.tools.each do |tool| %>
        <%= tool.name %>
    <% end %>
    <br>
</p>

<%= link_to 'Edit', edit_cookbook_path(@cookbook) %> |
<%= link_to 'Back', cookbooks_path %>